import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { EnergyPeriodChart } from './EnergyPeriodChart';
import { ThemeProvider } from '@/contexts/ThemeContext';
import { SocketProvider } from '@/contexts/SocketContext';
import * as useEnergyByPeriodModule from '@/features/dashboard/hooks/useEnergyByPeriod';
import * as useChartRealTimeUpdatesModule from '@/features/dashboard/hooks/useChartRealTimeUpdates';

// Mock the hooks
vi.mock('@/features/dashboard/hooks/useEnergyByPeriod');
vi.mock('@/features/dashboard/hooks/useChartRealTimeUpdates');

describe('EnergyPeriodChart - Real-Time Updates Integration', () => {
  let queryClient: QueryClient;

  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: {
          retry: false,
        },
      },
    });

    // Mock useChartRealTimeUpdates to do nothing by default
    vi.spyOn(useChartRealTimeUpdatesModule, 'useChartRealTimeUpdates').mockImplementation(() => {});
  });

  afterEach(() => {
    vi.clearAllMocks();
    queryClient.clear();
  });

  const renderWithProviders = (component: React.ReactElement) => {
    return render(
      <QueryClientProvider client={queryClient}>
        <ThemeProvider>
          <SocketProvider>{component}</SocketProvider>
        </ThemeProvider>
      </QueryClientProvider>
    );
  };

  it('should call useChartRealTimeUpdates hook on mount', () => {
    // Mock useEnergyByPeriod to return loading state
    vi.spyOn(useEnergyByPeriodModule, 'useEnergyByPeriod').mockReturnValue({
      data: undefined,
      isLoading: true,
      error: null,
      refetch: vi.fn(),
    });

    const useChartRealTimeUpdatesSpy = vi.spyOn(
      useChartRealTimeUpdatesModule,
      'useChartRealTimeUpdates'
    );

    renderWithProviders(<EnergyPeriodChart />);

    // Verify the hook was called
    expect(useChartRealTimeUpdatesSpy).toHaveBeenCalledTimes(1);
  });

  it('should render chart with data and real-time updates enabled', async () => {
    // Mock useEnergyByPeriod to return sample data
    const mockData = {
      metric: 'energy' as const,
      granularity: 'day' as const,
      dataPoints: [
        { timestamp: '2024-01-13T00:00:00Z', value: 2.5, label: 'Jan 13' },
        { timestamp: '2024-01-14T00:00:00Z', value: 3.2, label: 'Jan 14' },
        { timestamp: '2024-01-15T00:00:00Z', value: 2.8, label: 'Jan 15' },
      ],
      metadata: {
        unit: 'kWh',
        aggregation: 'sum' as const,
      },
    };

    vi.spyOn(useEnergyByPeriodModule, 'useEnergyByPeriod').mockReturnValue({
      data: mockData,
      isLoading: false,
      error: null,
      refetch: vi.fn(),
    });

    const useChartRealTimeUpdatesSpy = vi.spyOn(
      useChartRealTimeUpdatesModule,
      'useChartRealTimeUpdates'
    );

    renderWithProviders(<EnergyPeriodChart />);

    // Verify the real-time updates hook is active
    expect(useChartRealTimeUpdatesSpy).toHaveBeenCalledTimes(1);

    // Verify chart title is rendered
    await waitFor(() => {
      expect(screen.getByText('Energy Generated by Period')).toBeInTheDocument();
    });
  });

  it('should maintain real-time updates subscription across filter changes', async () => {
    // Mock useEnergyByPeriod
    vi.spyOn(useEnergyByPeriodModule, 'useEnergyByPeriod').mockReturnValue({
      data: undefined,
      isLoading: false,
      error: null,
      refetch: vi.fn(),
    });

    const useChartRealTimeUpdatesSpy = vi.spyOn(
      useChartRealTimeUpdatesModule,
      'useChartRealTimeUpdates'
    );

    const { rerender } = renderWithProviders(<EnergyPeriodChart />);

    // Initial render should call the hook
    expect(useChartRealTimeUpdatesSpy).toHaveBeenCalledTimes(1);

    // Rerender (simulating filter change or other state update)
    rerender(
      <QueryClientProvider client={queryClient}>
        <ThemeProvider>
          <SocketProvider>
            <EnergyPeriodChart />
          </SocketProvider>
        </ThemeProvider>
      </QueryClientProvider>
    );

    // Hook should be called on each render to maintain subscription
    expect(useChartRealTimeUpdatesSpy).toHaveBeenCalledTimes(2);
  });

  it('should render loading state while maintaining real-time subscription', () => {
    // Mock useEnergyByPeriod to return loading state
    vi.spyOn(useEnergyByPeriodModule, 'useEnergyByPeriod').mockReturnValue({
      data: undefined,
      isLoading: true,
      error: null,
      refetch: vi.fn(),
    });

    const useChartRealTimeUpdatesSpy = vi.spyOn(
      useChartRealTimeUpdatesModule,
      'useChartRealTimeUpdates'
    );

    renderWithProviders(<EnergyPeriodChart />);

    // Verify hook is called even during loading
    expect(useChartRealTimeUpdatesSpy).toHaveBeenCalledTimes(1);

    // Verify loading state is displayed
    expect(screen.getByText('Energy Generated by Period')).toBeInTheDocument();
  });

  it('should render empty state while maintaining real-time subscription', () => {
    // Mock useEnergyByPeriod to return empty data
    const mockEmptyData = {
      metric: 'energy' as const,
      granularity: 'day' as const,
      dataPoints: [],
      metadata: {
        unit: 'kWh',
        aggregation: 'sum' as const,
      },
    };

    vi.spyOn(useEnergyByPeriodModule, 'useEnergyByPeriod').mockReturnValue({
      data: mockEmptyData,
      isLoading: false,
      error: null,
      refetch: vi.fn(),
    });

    const useChartRealTimeUpdatesSpy = vi.spyOn(
      useChartRealTimeUpdatesModule,
      'useChartRealTimeUpdates'
    );

    renderWithProviders(<EnergyPeriodChart />);

    // Verify hook is called even with empty data
    expect(useChartRealTimeUpdatesSpy).toHaveBeenCalledTimes(1);
  });

  it('should render error state while maintaining real-time subscription', () => {
    // Mock useEnergyByPeriod to return error state
    vi.spyOn(useEnergyByPeriodModule, 'useEnergyByPeriod').mockReturnValue({
      data: undefined,
      isLoading: false,
      error: new Error('Failed to fetch energy data'),
      refetch: vi.fn(),
    });

    const useChartRealTimeUpdatesSpy = vi.spyOn(
      useChartRealTimeUpdatesModule,
      'useChartRealTimeUpdates'
    );

    renderWithProviders(<EnergyPeriodChart />);

    // Verify hook is called even during error state
    expect(useChartRealTimeUpdatesSpy).toHaveBeenCalledTimes(1);
  });

  it('should use daily filter as default', () => {
    // Mock useEnergyByPeriod with spy to check arguments
    const useEnergyByPeriodSpy = vi
      .spyOn(useEnergyByPeriodModule, 'useEnergyByPeriod')
      .mockReturnValue({
        data: undefined,
        isLoading: true,
        error: null,
        refetch: vi.fn(),
      });

    renderWithProviders(<EnergyPeriodChart />);

    // Verify the hook was called with 'daily' as default
    expect(useEnergyByPeriodSpy).toHaveBeenCalledWith('daily');
  });

  it('should respect custom defaultPeriodFilter prop', () => {
    // Mock useEnergyByPeriod with spy to check arguments
    const useEnergyByPeriodSpy = vi
      .spyOn(useEnergyByPeriodModule, 'useEnergyByPeriod')
      .mockReturnValue({
        data: undefined,
        isLoading: true,
        error: null,
        refetch: vi.fn(),
      });

    renderWithProviders(<EnergyPeriodChart defaultPeriodFilter="hourly" />);

    // Verify the hook was called with 'hourly'
    expect(useEnergyByPeriodSpy).toHaveBeenCalledWith('hourly');
  });
});
