import {
  Injectable,
  Logger,
  NotFoundException,
  BadRequestException,
  ForbiddenException,
} from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import * as fs from 'fs';
import * as path from 'path';
import {
  Report,
  ReportDocument,
  ReportType,
  ReportFormat,
} from './schemas/report.schema';
import { GenerateReportDto } from './dto';
import { AnalyticsService } from '../analytics/analytics.service';
import { UsersService } from '../users/users.service';
import { PdfGeneratorService } from './generators/pdf-generator.service';
import { ExcelGeneratorService } from './generators/excel-generator.service';

/**
 * Reports Service
 *
 * Handles report generation, storage, and retrieval.
 *
 * Responsibilities:
 * - Generate PDF and Excel reports
 * - Store report files and metadata
 * - Manage report lifecycle (create, list, download, delete)
 * - Enforce ownership and access control
 *
 * Data Sources:
 * - AnalyticsService: Primary data source for all metrics
 * - UsersService: For "Generated By" information
 *
 * Storage:
 * - Files: ./uploads/reports/ directory
 * - Metadata: MongoDB (Report collection)
 *
 * Principles:
 * - No direct database queries (use services)
 * - All calculations delegated to AnalyticsService
 * - Ownership validation on all operations
 */
@Injectable()
export class ReportsService {
  private readonly logger = new Logger(ReportsService.name);
  private readonly UPLOADS_DIR = path.join(process.cwd(), 'uploads', 'reports');
  private readonly REPORT_RETENTION_DAYS = 30;

  constructor(
    @InjectModel(Report.name)
    private reportModel: Model<ReportDocument>,
    private analyticsService: AnalyticsService,
    private usersService: UsersService,
    private pdfGeneratorService: PdfGeneratorService,
    private excelGeneratorService: ExcelGeneratorService,
  ) {
    // Ensure uploads directory exists
    this.ensureUploadsDirectory();
  }

  /**
   * Generate Report
   *
   * Main method for generating reports.
   *
   * Process:
   * 1. Validate request parameters
   * 2. Calculate date range based on report type
   * 3. Fetch data from AnalyticsService
   * 4. Generate file (PDF or Excel)
   * 5. Save file to file system
   * 6. Save metadata to MongoDB
   * 7. Return report metadata
   *
   * @param dto - Report generation parameters
   * @param userId - ID of user generating the report
   * @returns Generated report metadata
   */
  async generate(
    dto: GenerateReportDto,
    userId: string,
  ): Promise<ReportDocument> {
    this.logger.log(
      `Generating ${dto.type} report in ${dto.format} format for user ${userId}`,
    );

    // Validate and calculate date range
    const { startDate, endDate } = this.calculateDateRange(dto);

    // Fetch data from AnalyticsService
    const reportData = await this.fetchReportData(
      dto.type,
      startDate,
      endDate,
      dto.electricityRate,
      dto.includeSections,
      dto.aggregation,
    );

    // Get user info for "Generated By"
    const user = await this.usersService.findById(userId);

    // Generate file
    const { filePath, fileName, fileSize } = await this.generateFile(
      dto.format,
      dto.type,
      startDate,
      endDate,
      reportData,
      user,
    );

    // Calculate expiration date (30 days from now)
    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + this.REPORT_RETENTION_DAYS);

    // Save metadata to database
    const report = new this.reportModel({
      type: dto.type,
      format: dto.format,
      fileName,
      filePath,
      fileSize,
      generatedBy: new Types.ObjectId(userId),
      startDate,
      endDate,
      parameters: {
        electricityRate: dto.electricityRate,
        includeSections: dto.includeSections,
        aggregation: dto.aggregation,
      },
      summary: reportData.summary,
      downloadCount: 0,
      expiresAt,
    });

    await report.save();

    this.logger.log(`Report generated successfully: ${report.id}`);

    return report;
  }

  /**
   * List Reports
   *
   * Retrieves all reports for a user with pagination.
   *
   * @param userId - User ID
   * @param page - Page number (default: 1)
   * @param limit - Items per page (default: 10)
   * @param type - Optional filter by type
   * @param format - Optional filter by format
   * @returns Paginated list of reports
   */
  async findAll(
    userId: string,
    page: number = 1,
    limit: number = 10,
    type?: ReportType,
    format?: ReportFormat,
  ): Promise<{ data: ReportDocument[]; meta: any }> {
    const query: any = { generatedBy: new Types.ObjectId(userId) };

    // Apply filters
    if (type) {
      query.type = type;
    }
    if (format) {
      query.format = format;
    }

    const total = await this.reportModel.countDocuments(query);
    const totalPages = Math.ceil(total / limit);
    const skip = (page - 1) * limit;

    const reports = await this.reportModel
      .find(query)
      .sort({ createdAt: -1 }) // Newest first
      .skip(skip)
      .limit(limit)
      .exec();

    return {
      data: reports,
      meta: {
        total,
        page,
        limit,
        totalPages,
      },
    };
  }

  /**
   * Find One Report
   *
   * Retrieves a single report by ID.
   *
   * @param id - Report ID
   * @param userId - User ID (for ownership validation)
   * @returns Report document
   * @throws NotFoundException if report not found
   * @throws ForbiddenException if user doesn't own report
   */
  async findOne(id: string, userId: string): Promise<ReportDocument> {
    const report = await this.reportModel.findById(id).exec();

    if (!report) {
      throw new NotFoundException(`Report with ID ${id} not found`);
    }

    // Validate ownership
    if (report.generatedBy.toString() !== userId) {
      throw new ForbiddenException('You do not have access to this report');
    }

    return report;
  }

  /**
   * Download Report
   *
   * Returns a file stream for downloading the report.
   * Increments download count.
   *
   * @param id - Report ID
   * @param userId - User ID (for ownership validation)
   * @returns File stream
   * @throws NotFoundException if report or file not found
   * @throws ForbiddenException if user doesn't own report
   */
  async download(
    id: string,
    userId: string,
  ): Promise<{ stream: fs.ReadStream; report: ReportDocument }> {
    const report = await this.findOne(id, userId);
    // Validate file exists
    const fullPath = path.join(process.cwd(), report.filePath);
    if (!fs.existsSync(fullPath)) {
      throw new NotFoundException('Report file not found');
    }

    // Validate file is within uploads directory (security)
    const realPath = fs.realpathSync(fullPath);
    if (!realPath.startsWith(this.UPLOADS_DIR)) {
      throw new ForbiddenException('Invalid file path');
    }

    // Increment download count
    await this.reportModel.findByIdAndUpdate(id, {
      $inc: { downloadCount: 1 },
    });

    // Create read stream
    const stream = fs.createReadStream(fullPath);

    return { stream, report };
  }

  /**
   * Delete Report
   *
   * Deletes a report and its file.
   *
   * @param id - Report ID
   * @param userId - User ID (for ownership validation)
   * @returns Deleted report
   * @throws NotFoundException if report not found
   * @throws ForbiddenException if user doesn't own report
   */
  async delete(id: string, userId: string): Promise<ReportDocument> {
    const report = await this.findOne(id, userId);

    // Delete file
    const fullPath = path.join(process.cwd(), report.filePath);
    if (fs.existsSync(fullPath)) {
      fs.unlinkSync(fullPath);
      this.logger.log(`Deleted report file: ${fullPath}`);
    }

    // Delete metadata
    await this.reportModel.findByIdAndDelete(id);

    this.logger.log(`Deleted report: ${id}`);

    return report;
  }

  /**
   * Calculate Date Range
   *
   * Calculates startDate and endDate based on report type.
   *
   * @param dto - Report generation parameters
   * @returns { startDate, endDate } in YYYY-MM-DD format
   * @throws BadRequestException if parameters are invalid
   */
  private calculateDateRange(dto: GenerateReportDto): {
    startDate: string;
    endDate: string;
  } {
    // New report types (energy_monitoring, historical_analytics, system_diagnostics, system_summary)
    // always require startDate and endDate
    if (
      dto.type === ReportType.ENERGY_MONITORING ||
      dto.type === ReportType.HISTORICAL_ANALYTICS ||
      dto.type === ReportType.SYSTEM_DIAGNOSTICS ||
      dto.type === ReportType.SYSTEM_SUMMARY ||
      dto.type === ReportType.CUSTOM
    ) {
      if (!dto.startDate || !dto.endDate) {
        throw new BadRequestException(
          'startDate and endDate are required for this report type',
        );
      }

      const start = new Date(dto.startDate);
      const end = new Date(dto.endDate);

      if (end < start) {
        throw new BadRequestException(
          'endDate must be after or equal to startDate',
        );
      }

      return {
        startDate: dto.startDate,
        endDate: dto.endDate,
      };
    }

    // Legacy report types (daily, weekly, monthly)
    if (!dto.year) {
      throw new BadRequestException(
        'year is required for daily/weekly/monthly reports',
      );
    }

    if (dto.type === ReportType.DAILY) {
      // Daily: Single day
      if (!dto.month || !dto.day) {
        throw new BadRequestException(
          'month and day are required for daily reports',
        );
      }

      const date = new Date(dto.year, dto.month - 1, dto.day);
      const dateStr = date.toISOString().split('T')[0];

      return {
        startDate: dateStr,
        endDate: dateStr,
      };
    }

    if (dto.type === ReportType.WEEKLY) {
      // Weekly: Monday to Sunday
      if (!dto.month || !dto.day) {
        throw new BadRequestException(
          'month and day are required for weekly reports',
        );
      }

      const date = new Date(dto.year, dto.month - 1, dto.day);
      const monday = this.getMondayOfWeek(date);
      const sunday = new Date(monday);
      sunday.setDate(monday.getDate() + 6);

      return {
        startDate: monday.toISOString().split('T')[0],
        endDate: sunday.toISOString().split('T')[0],
      };
    }

    if (dto.type === ReportType.MONTHLY) {
      // Monthly: First to last day of month
      if (!dto.month) {
        throw new BadRequestException('month is required for monthly reports');
      }

      const firstDay = new Date(dto.year, dto.month - 1, 1);
      const lastDay = new Date(dto.year, dto.month, 0);

      return {
        startDate: firstDay.toISOString().split('T')[0],
        endDate: lastDay.toISOString().split('T')[0],
      };
    }

    throw new BadRequestException('Invalid report type');
  }

  /**
   * Fetch Report Data
   *
   * Fetches all data needed for the report from AnalyticsService.
   * Validates data availability and returns appropriate error messages.
   *
   * @param type - Report type
   * @param startDate - Start date
   * @param endDate - End date
   * @param electricityRate - Custom electricity rate (optional)
   * @param includeSections - Sections to include (optional)
   * @param aggregation - Data aggregation period (optional)
   * @returns Report data
   * @throws BadRequestException if no data available
   */
  private async fetchReportData(
    type: ReportType,
    startDate: string,
    endDate: string,
    electricityRate?: number,
    includeSections?: string[],
    aggregation?: 'hourly' | 'daily' | 'weekly',
  ): Promise<any> {
    this.logger.debug(
      `Fetching data for ${type} report from ${startDate} to ${endDate}`,
    );

    // Calculate period days
    const start = new Date(startDate);
    const end = new Date(endDate);
    const periodDays =
      Math.ceil((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24)) + 1;

    // Fetch data based on report type
    let energySummary;
    
    // New report types - fetch data based on date range
    if (
      type === ReportType.ENERGY_MONITORING ||
      type === ReportType.HISTORICAL_ANALYTICS ||
      type === ReportType.SYSTEM_DIAGNOSTICS ||
      type === ReportType.SYSTEM_SUMMARY
    ) {
      // For new report types, use custom date range
      // This will be enhanced when we add proper date range queries to analytics service
      const year = new Date(startDate).getFullYear();
      const month = new Date(startDate).getMonth() + 1;
      
      try {
        energySummary = await this.analyticsService.getMonthlySummary(
          year,
          month,
        );
      } catch (error) {
        this.logger.warn(`No data available for period: ${error.message}`);
        // Return empty data structure
        energySummary = {
          totalEnergyKWh: 0,
          avgPowerW: 0,
          peakPowerW: 0,
          readingCount: 0,
        };
      }

      // Validate data availability
      if (energySummary.readingCount === 0) {
        this.logger.warn(`No data available for ${type} report, generating report with zero values`);
        // Don't throw error - allow report generation with zero values
        // This lets admins see report structure even without data
      }
    } else {
      // Legacy report types
      if (type === ReportType.DAILY) {
        energySummary = await this.analyticsService.getDailySummary(startDate);
      } else if (type === ReportType.WEEKLY) {
        energySummary = await this.analyticsService.getWeeklySummary(
          new Date(startDate),
        );
      } else if (type === ReportType.MONTHLY) {
        const year = new Date(startDate).getFullYear();
        const month = new Date(startDate).getMonth() + 1;
        energySummary = await this.analyticsService.getMonthlySummary(
          year,
          month,
        );
      } else {
        // Custom: Use monthly summary as fallback
        energySummary = await this.analyticsService.getMonthlySummary();
      }
    }

    // Calculate environmental impact
    const environmentalImpact =
      this.analyticsService.calculateEnvironmentalImpact(
        energySummary.totalEnergyKWh,
      );

    // Calculate cost savings
    const costSavings = this.analyticsService.calculateCostSavings(
      energySummary.totalEnergyKWh,
      periodDays,
      electricityRate,
    );

    // Get peak generation
    let peakGeneration;
    try {
      peakGeneration = await this.analyticsService.getPeakGeneration(
        startDate,
        endDate,
      );
    } catch (error) {
      this.logger.warn(`Could not fetch peak generation: ${error.message}`);
      peakGeneration = { power: energySummary.peakPowerW || 0, timestamp: new Date() };
    }

    return {
      energySummary,
      environmentalImpact,
      costSavings,
      peakGeneration,
      includeSections: includeSections || [],
      aggregation: aggregation || 'daily',
      summary: {
        totalEnergyKWh: energySummary.totalEnergyKWh,
        avgPowerW: energySummary.avgPowerW,
        peakPowerW: energySummary.peakPowerW,
        co2AvoidedKg: environmentalImpact.co2AvoidedKg,
        costSavingsUSD: costSavings.totalSavings,
        readingCount: energySummary.readingCount,
      },
    };
  }

  /**
   * Generate File
   *
   * Generates PDF or Excel file.
   *
   * @param format - File format (pdf | excel)
   * @param type - Report type
   * @param startDate - Start date
   * @param endDate - End date
   * @param reportData - Report data
   * @param user - User who generated the report
   * @returns { filePath, fileName, fileSize }
   */
  private async generateFile(
    format: ReportFormat,
    type: ReportType,
    startDate: string,
    endDate: string,
    reportData: any,
    user: any,
  ): Promise<{ filePath: string; fileName: string; fileSize: number }> {
    // Generate filename
    const fileName = this.generateFileName(type, startDate, endDate, format);
    const filePath = path.join(this.UPLOADS_DIR, fileName);

    // Generate file
    if (format === ReportFormat.PDF) {
      // Phase 3 - PDF generation ✅
      await this.pdfGeneratorService.generate(
        filePath,
        type,
        startDate,
        endDate,
        reportData,
        user,
      );
      this.logger.log(`PDF generated: ${fileName}`);
    } else {
      // Phase 4 - Excel generation ✅
      await this.excelGeneratorService.generate(
        filePath,
        type,
        startDate,
        endDate,
        reportData,
        user,
      );
      this.logger.log(`Excel generated: ${fileName}`);
    }

    // Get file size
    const stats = fs.statSync(filePath);
    const fileSize = stats.size;

    // Return relative path for storage
    const relativePath = path.join('uploads', 'reports', fileName);

    return {
      filePath: relativePath,
      fileName,
      fileSize,
    };
  }

  /**
   * Generate File Name
   *
   * Creates a unique filename for the report.
   *
   * Format: {type}-report-{period}-{timestamp}.{ext}
   *
   * Examples:
   * - energy-monitoring-report-2026-09-01-to-2026-09-19-1726740000000.pdf
   * - historical-analytics-report-2026-09-1726740000000.xlsx
   */
  private generateFileName(
    type: ReportType,
    startDate: string,
    endDate: string,
    format: ReportFormat,
  ): string {
    const timestamp = Date.now();
    let period: string;

    // New report types - use descriptive names
    if (
      type === ReportType.ENERGY_MONITORING ||
      type === ReportType.HISTORICAL_ANALYTICS ||
      type === ReportType.SYSTEM_DIAGNOSTICS ||
      type === ReportType.SYSTEM_SUMMARY
    ) {
      if (startDate === endDate) {
        period = startDate;
      } else {
        period = `${startDate}-to-${endDate}`;
      }
    } else if (type === ReportType.DAILY) {
      period = startDate; // 2026-07-18
    } else if (type === ReportType.WEEKLY) {
      const weekNumber = this.getWeekNumber(new Date(startDate));
      const year = new Date(startDate).getFullYear();
      period = `${year}-W${String(weekNumber).padStart(2, '0')}`;
    } else if (type === ReportType.MONTHLY) {
      period = startDate.substring(0, 7); // 2026-07
    } else {
      period = `${startDate}-to-${endDate}`;
    }

    const ext = format === ReportFormat.PDF ? 'pdf' : 'xlsx';

    // Replace underscores with hyphens for consistency
    const typeStr = type.replace(/_/g, '-');

    return `${typeStr}-report-${period}-${timestamp}.${ext}`;
  }

  /**
   * Ensure Uploads Directory Exists
   *
   * Creates the uploads/reports directory if it doesn't exist.
   */
  private ensureUploadsDirectory(): void {
    if (!fs.existsSync(this.UPLOADS_DIR)) {
      fs.mkdirSync(this.UPLOADS_DIR, { recursive: true });
      this.logger.log(`Created uploads directory: ${this.UPLOADS_DIR}`);
    }
  }

  /**
   * Helper: Get Monday of Week
   */
  private getMondayOfWeek(date: Date): Date {
    const d = new Date(date);
    const day = d.getDay();
    const diff = d.getDate() - day + (day === 0 ? -6 : 1);
    return new Date(d.setDate(diff));
  }

  /**
   * Helper: Get Week Number
   */
  private getWeekNumber(date: Date): number {
    const d = new Date(date);
    d.setHours(0, 0, 0, 0);
    d.setDate(d.getDate() + 4 - (d.getDay() || 7));
    const yearStart = new Date(d.getFullYear(), 0, 1);
    return Math.ceil(((d.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
  }
}
