import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { Report, ReportSchema } from './schemas/report.schema';
import { ReportsService } from './reports.service';
import { ReportsController } from './reports.controller';
import { AnalyticsModule } from '../analytics/analytics.module';
import { UsersModule } from '../users/users.module';
import { PdfGeneratorService } from './generators/pdf-generator.service';
import { ExcelGeneratorService } from './generators/excel-generator.service';

/**
 * Reports Module
 *
 * Handles energy report generation, storage, and management.
 *
 * Responsibilities:
 * - Generate PDF and Excel reports
 * - Store report files and metadata
 * - Manage report lifecycle (create, list, download, delete)
 * - Auto-delete expired reports (30-day retention)
 *
 * Components:
 * - Schema: Report (MongoDB model for metadata)
 * - Service: ReportsService (business logic)
 * - Controller: ReportsController (REST API)
 *
 * Dependencies:
 * - MongooseModule: Database operations
 * - AnalyticsModule: Data source for reports
 * - UsersModule: "Generated By" information
 * - AuthModule: JWT authentication (imported via guards)
 *
 * Storage:
 * - Files: ./uploads/reports/ directory
 * - Metadata: MongoDB (reports collection)
 * - Retention: 30 days (TTL index)
 *
 * Authentication:
 * - All endpoints require JWT authentication
 * - Users can only access their own reports
 * - JwtAuthGuard applied at controller level
 *
 * Report Types:
 * - Daily: Single day report
 * - Weekly: Monday to Sunday report
 * - Monthly: Full month report
 * - Custom: User-specified date range
 *
 * Report Formats:
 * - PDF: Professional PDF document (PDFKit)
 * - Excel: Excel spreadsheet (ExcelJS)
 *
 * Implementation Phases:
 * - Phase 1: Core infrastructure ✓ (current)
 * - Phase 2: Data integration ⏳
 * - Phase 3: PDF generation ⏳
 * - Phase 4: Excel generation ⏳
 * - Phase 5: API endpoints ⏳
 * - Phase 6: Testing & cleanup ⏳
 */
@Module({
  imports: [
    // Register Report schema with Mongoose
    MongooseModule.forFeature([
      {
        name: Report.name,
        schema: ReportSchema,
      },
    ]),

    // Import AnalyticsModule to access AnalyticsService
    AnalyticsModule,

    // Import UsersModule to access UsersService
    UsersModule,
  ],
  controllers: [ReportsController],
  providers: [ReportsService, PdfGeneratorService, ExcelGeneratorService],
  exports: [ReportsService], // Export for potential future use
})
export class ReportsModule {}
