/**
 * Role-Based Access Tests for Dashboard Charts
 * 
 * This test file verifies that the Energy Monitoring & Analytics Charts
 * are accessible to both public users and system administrators, and that
 * no admin-only controls appear within chart components.
 * 
 * Requirements Validated:
 * - 10.1: Chart_Access_Control SHALL allow both Public_User and System_Administrator roles to view all charts
 * - 10.2: Use existing getUserRole function from frontend/src/lib/permissions.ts
 * - 10.3: No admin-only controls should appear in chart components
 * - 10.7: Maintain existing PublicUserBanner display for unauthenticated users
 * - 10.8: No separate chart views/routes for public vs admin users
 */

import { render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { vi, describe, it, expect, beforeEach, afterEach } from 'vitest';
import { DashboardPage } from './DashboardPage';
import { AuthContext } from '@/contexts/AuthContext';
import { ThemeContext } from '@/contexts/ThemeContext';
import { SocketContext } from '@/contexts/SocketContext';
import { getUserRole } from '@/lib/permissions';
import type { User } from '@/types';

// Mock all API services
vi.mock('@/api/services/analytics.service', () => ({
  analyticsService: {
    getTimeSeries: vi.fn().mockResolvedValue({
      metric: 'power',
      granularity: 'hour',
      dataPoints: [
        { timestamp: '2024-01-15T12:00:00Z', value: 5.2 },
        { timestamp: '2024-01-15T13:00:00Z', value: 4.8 },
      ],
      metadata: { unit: 'W' },
    }),
    getDashboardAnalytics: vi.fn().mockResolvedValue({
      today: { energy: 12.5, power: 5.2 },
      yesterday: { energy: 10.3, power: 4.8 },
    }),
  },
}));

vi.mock('@/api/services/sensor.service', () => ({
  sensorService: {
    getLatestReadings: vi.fn().mockResolvedValue([
      {
        sensorId: 'sensor-1',
        voltage: 5.2,
        current: 0.48,
        power: 2.5,
        energy: 12.5,
        timestamp: '2024-01-15T12:00:00Z',
      },
    ]),
  },
}));

// Mock socket context
const mockSocket = {
  on: vi.fn(),
  off: vi.fn(),
  emit: vi.fn(),
};

const mockSocketContext = {
  socket: mockSocket as any,
  isConnected: true,
  connect: vi.fn(),
  disconnect: vi.fn(),
};

/**
 * Helper function to render DashboardPage with all required providers
 */
function renderDashboardPage(authState: {
  isAuthenticated: boolean;
  user: User | null;
}) {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        retry: false,
        cacheTime: 0,
      },
    },
  });

  const mockAuthContext = {
    ...authState,
    login: vi.fn(),
    logout: vi.fn(),
    isLoading: false,
  };

  const mockThemeContext = {
    theme: 'light' as const,
    toggleTheme: vi.fn(),
  };

  return render(
    <QueryClientProvider client={queryClient}>
      <AuthContext.Provider value={mockAuthContext}>
        <ThemeContext.Provider value={mockThemeContext}>
          <SocketContext.Provider value={mockSocketContext}>
            <DashboardPage />
          </SocketContext.Provider>
        </ThemeContext.Provider>
      </AuthContext.Provider>
    </QueryClientProvider>
  );
}

describe('DashboardPage - Role-Based Access for Charts', () => {
  let queryClient: QueryClient;

  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: {
          retry: false,
        },
      },
    });
    vi.clearAllMocks();
  });

  afterEach(() => {
    queryClient.clear();
  });

  describe('Requirement 10.1: Both Public_User and System_Administrator can view all charts', () => {
    it('should render all charts for public users (unauthenticated)', async () => {
      renderDashboardPage({
        isAuthenticated: false,
        user: null,
      });

      // Wait for charts to be rendered
      await waitFor(() => {
        // Power Generation Chart
        expect(screen.getByText(/Power Generation Over Time/i)).toBeInTheDocument();
        
        // Voltage and Current Charts
        expect(screen.getByText(/Voltage Trend/i)).toBeInTheDocument();
        expect(screen.getByText(/Current Trend/i)).toBeInTheDocument();
        
        // Energy Period Chart
        expect(screen.getByText(/Energy Generated by Period/i)).toBeInTheDocument();
        
        // Cumulative Energy Chart
        expect(screen.getByText(/Cumulative Energy Generated/i)).toBeInTheDocument();
      });
    });

    it('should render all charts for system administrators (authenticated)', async () => {
      const mockAdminUser: User = {
        id: 'admin-1',
        email: 'admin@ecostep.com',
        name: 'Admin User',
        role: 'admin',
      };

      renderDashboardPage({
        isAuthenticated: true,
        user: mockAdminUser,
      });

      // Wait for charts to be rendered
      await waitFor(() => {
        // Power Generation Chart
        expect(screen.getByText(/Power Generation Over Time/i)).toBeInTheDocument();
        
        // Voltage and Current Charts
        expect(screen.getByText(/Voltage Trend/i)).toBeInTheDocument();
        expect(screen.getByText(/Current Trend/i)).toBeInTheDocument();
        
        // Energy Period Chart
        expect(screen.getByText(/Energy Generated by Period/i)).toBeInTheDocument();
        
        // Cumulative Energy Chart
        expect(screen.getByText(/Cumulative Energy Generated/i)).toBeInTheDocument();
      });
    });
  });

  describe('Requirement 10.2: Use getUserRole function to confirm role detection', () => {
    it('should correctly identify public user role', () => {
      const role = getUserRole(false, null);
      expect(role).toBe('public');
    });

    it('should correctly identify admin user role', () => {
      const mockAdminUser: User = {
        id: 'admin-1',
        email: 'admin@ecostep.com',
        name: 'Admin User',
        role: 'admin',
      };

      const role = getUserRole(true, mockAdminUser);
      expect(role).toBe('admin');
    });

    it('should use getUserRole function in DashboardPage component', async () => {
      renderDashboardPage({
        isAuthenticated: false,
        user: null,
      });

      // The component should call getUserRole internally
      // We verify this by checking that role-dependent UI renders correctly
      await waitFor(() => {
        // Public User Banner should be visible for public users
        expect(screen.getByText(/create an account/i)).toBeInTheDocument();
      });
    });
  });

  describe('Requirement 10.3: No admin-only controls in chart components', () => {
    it('should not display admin-only buttons in chart components for public users', async () => {
      renderDashboardPage({
        isAuthenticated: false,
        user: null,
      });

      await waitFor(() => {
        expect(screen.getByText(/Power Generation Over Time/i)).toBeInTheDocument();
      });

      // Chart components should ONLY have filter buttons (Today, 7 Days, 30 Days, etc.)
      // They should NOT have:
      // - Configure/Settings buttons
      // - Delete buttons
      // - Edit buttons
      // - Export buttons (these are on dashboard level, not chart level)
      
      // Verify filter buttons exist (these are allowed for all users)
      expect(screen.getByRole('button', { name: /Today/i })).toBeInTheDocument();
      expect(screen.getByRole('button', { name: /7 Days/i })).toBeInTheDocument();
      
      // Verify no admin-specific chart controls exist
      const allButtons = screen.getAllByRole('button');
      const adminButtons = allButtons.filter(button => 
        button.textContent?.match(/configure|delete|edit|manage/i)
      );
      
      // Within charts section, there should be no admin controls
      expect(adminButtons.length).toBe(0);
    });

    it('should not display admin-only buttons in chart components for admin users', async () => {
      const mockAdminUser: User = {
        id: 'admin-1',
        email: 'admin@ecostep.com',
        name: 'Admin User',
        role: 'admin',
      };

      renderDashboardPage({
        isAuthenticated: true,
        user: mockAdminUser,
      });

      await waitFor(() => {
        expect(screen.getByText(/Power Generation Over Time/i)).toBeInTheDocument();
      });

      // Even for admin users, chart components themselves should not have admin controls
      // Admin controls (Settings, Export, etc.) are at the dashboard level, not chart level
      
      // Verify filter buttons exist
      expect(screen.getByRole('button', { name: /Today/i })).toBeInTheDocument();
      
      // Chart components should not have admin-specific controls
      // (Admin controls exist at dashboard level: Settings, Export buttons in header)
      const chartContainer = screen.getByText(/Power Generation Over Time/i).closest('div');
      
      // Within the chart container, there should be no configure/delete/manage buttons
      if (chartContainer) {
        const chartButtons = chartContainer.querySelectorAll('button');
        const adminChartButtons = Array.from(chartButtons).filter(button =>
          button.textContent?.match(/configure|delete|manage/i)
        );
        expect(adminChartButtons.length).toBe(0);
      }
    });
  });

  describe('Requirement 10.7: Maintain PublicUserBanner display for unauthenticated users', () => {
    it('should display PublicUserBanner for public users', async () => {
      renderDashboardPage({
        isAuthenticated: false,
        user: null,
      });

      // PublicUserBanner should be visible
      await waitFor(() => {
        expect(screen.getByText(/create an account/i)).toBeInTheDocument();
      });
    });

    it('should NOT display PublicUserBanner for authenticated admin users', async () => {
      const mockAdminUser: User = {
        id: 'admin-1',
        email: 'admin@ecostep.com',
        name: 'Admin User',
        role: 'admin',
      };

      renderDashboardPage({
        isAuthenticated: true,
        user: mockAdminUser,
      });

      // Wait for page to render
      await waitFor(() => {
        expect(screen.getByText(/EcoStep Dashboard/i)).toBeInTheDocument();
      });

      // PublicUserBanner should NOT be visible
      expect(screen.queryByText(/create an account/i)).not.toBeInTheDocument();
    });

    it('should display charts below PublicUserBanner for public users', async () => {
      renderDashboardPage({
        isAuthenticated: false,
        user: null,
      });

      await waitFor(() => {
        // Both banner and charts should be visible
        expect(screen.getByText(/create an account/i)).toBeInTheDocument();
        expect(screen.getByText(/Power Generation Over Time/i)).toBeInTheDocument();
      });
    });
  });

  describe('Requirement 10.8: No separate chart views/routes for public vs admin', () => {
    it('should render the same DashboardPage component for public users', async () => {
      const { container: publicContainer } = renderDashboardPage({
        isAuthenticated: false,
        user: null,
      });

      await waitFor(() => {
        expect(screen.getByText(/Power Generation Over Time/i)).toBeInTheDocument();
      });

      // Verify all chart titles are present
      expect(screen.getByText(/Power Generation Over Time/i)).toBeInTheDocument();
      expect(screen.getByText(/Voltage Trend/i)).toBeInTheDocument();
      expect(screen.getByText(/Current Trend/i)).toBeInTheDocument();
      expect(screen.getByText(/Energy Generated by Period/i)).toBeInTheDocument();
      expect(screen.getByText(/Cumulative Energy Generated/i)).toBeInTheDocument();
    });

    it('should render the same DashboardPage component for admin users', async () => {
      const mockAdminUser: User = {
        id: 'admin-1',
        email: 'admin@ecostep.com',
        name: 'Admin User',
        role: 'admin',
      };

      const { container: adminContainer } = renderDashboardPage({
        isAuthenticated: true,
        user: mockAdminUser,
      });

      await waitFor(() => {
        expect(screen.getByText(/Power Generation Over Time/i)).toBeInTheDocument();
      });

      // Verify all chart titles are present (same as public user)
      expect(screen.getByText(/Power Generation Over Time/i)).toBeInTheDocument();
      expect(screen.getByText(/Voltage Trend/i)).toBeInTheDocument();
      expect(screen.getByText(/Current Trend/i)).toBeInTheDocument();
      expect(screen.getByText(/Energy Generated by Period/i)).toBeInTheDocument();
      expect(screen.getByText(/Cumulative Energy Generated/i)).toBeInTheDocument();
    });

    it('should use ChartsLayoutContainer for both roles', async () => {
      // Render for public user
      const { unmount: unmountPublic } = renderDashboardPage({
        isAuthenticated: false,
        user: null,
      });

      await waitFor(() => {
        expect(screen.getByText(/Power Generation Over Time/i)).toBeInTheDocument();
      });

      const publicChartCount = screen.getAllByRole('heading', { level: 3 }).filter(
        heading => heading.textContent?.match(/Power|Voltage|Current|Energy/)
      ).length;

      unmountPublic();

      // Render for admin user
      const mockAdminUser: User = {
        id: 'admin-1',
        email: 'admin@ecostep.com',
        name: 'Admin User',
        role: 'admin',
      };

      renderDashboardPage({
        isAuthenticated: true,
        user: mockAdminUser,
      });

      await waitFor(() => {
        expect(screen.getByText(/Power Generation Over Time/i)).toBeInTheDocument();
      });

      const adminChartCount = screen.getAllByRole('heading', { level: 3 }).filter(
        heading => heading.textContent?.match(/Power|Voltage|Current|Energy/)
      ).length;

      // Both should have the same number of charts
      expect(publicChartCount).toBe(adminChartCount);
    });
  });

  describe('Chart Component Isolation - No role-based conditional rendering', () => {
    it('should not conditionally hide charts based on user role', async () => {
      // Test public user
      const { unmount: unmountPublic } = renderDashboardPage({
        isAuthenticated: false,
        user: null,
      });

      await waitFor(() => {
        expect(screen.getByText(/Power Generation Over Time/i)).toBeInTheDocument();
      });

      const publicChartTitles = [
        'Power Generation Over Time',
        'Voltage Trend',
        'Current Trend',
        'Energy Generated by Period',
        'Cumulative Energy Generated',
      ];

      publicChartTitles.forEach(title => {
        expect(screen.getByText(new RegExp(title, 'i'))).toBeInTheDocument();
      });

      unmountPublic();

      // Test admin user
      const mockAdminUser: User = {
        id: 'admin-1',
        email: 'admin@ecostep.com',
        name: 'Admin User',
        role: 'admin',
      };

      renderDashboardPage({
        isAuthenticated: true,
        user: mockAdminUser,
      });

      await waitFor(() => {
        expect(screen.getByText(/Power Generation Over Time/i)).toBeInTheDocument();
      });

      // Admin should see the same charts
      publicChartTitles.forEach(title => {
        expect(screen.getByText(new RegExp(title, 'i'))).toBeInTheDocument();
      });
    });
  });
});
