import { Injectable, Logger } from '@nestjs/common';
import * as ExcelJS from 'exceljs';
import { ReportType } from '../schemas/report.schema';

/**
 * Excel Generator Service
 * 
 * Generates professional Excel reports using ExcelJS.
 * 
 * Features:
 * - Multiple sheets (Summary, Details, Charts)
 * - Professional styling and formatting
 * - Conditional formatting
 * - Formulas for calculations
 * - Data tables with headers
 * 
 * Sheets:
 * 1. Summary - Key metrics and overview
 * 2. Energy Performance - Detailed statistics
 * 3. Environmental Impact - Green metrics
 * 4. Cost Savings - Financial analysis
 * 5. Raw Data - Detailed breakdowns (if applicable)
 */
@Injectable()
export class ExcelGeneratorService {
  private readonly logger = new Logger(ExcelGeneratorService.name);

  // Colors (Excel hex format)
  private readonly colors = {
    primary: 'FF2563EB', // Blue
    success: 'FF10B981', // Green
    warning: 'FFF59E0B', // Orange
    danger: 'FFEF4444', // Red
    gray: 'FF6B7280',
    lightGray: 'FFF3F4F6',
    darkGray: 'FF374151',
    white: 'FFFFFFFF',
  };

  /**
   * Generate Excel Report
   * 
   * Creates an Excel workbook with multiple sheets.
   * 
   * @param filePath - Path where Excel file will be saved
   * @param reportType - Type of report
   * @param startDate - Report start date
   * @param endDate - Report end date
   * @param reportData - Report data from AnalyticsService
   * @param user - User who generated the report
   * @returns Promise<void>
   */
  async generate(
    filePath: string,
    reportType: ReportType,
    startDate: string,
    endDate: string,
    reportData: any,
    user: any,
  ): Promise<void> {
    this.logger.log(`Generating Excel report: ${filePath}`);

    try {
      // Create workbook
      const workbook = new ExcelJS.Workbook();
      workbook.creator = user?.name || 'Energy Monitoring System';
      workbook.created = new Date();
      workbook.modified = new Date();
      workbook.properties.date1904 = false;

      // Add sheets
      this.addSummarySheet(workbook, reportType, startDate, endDate, reportData, user);
      this.addEnergyPerformanceSheet(workbook, reportData);
      this.addEnvironmentalImpactSheet(workbook, reportData);
      this.addCostSavingsSheet(workbook, reportData);

      if (reportData.peakGeneration) {
        this.addPeakGenerationSheet(workbook, reportData);
      }

      // Save workbook
      await workbook.xlsx.writeFile(filePath);
      this.logger.log(`Excel report generated successfully: ${filePath}`);
    } catch (error) {
      this.logger.error(`Error generating Excel: ${error.message}`);
      throw error;
    }
  }

  /**
   * Add Summary Sheet
   * 
   * Overview sheet with key metrics.
   */
  private addSummarySheet(
    workbook: ExcelJS.Workbook,
    reportType: ReportType,
    startDate: string,
    endDate: string,
    reportData: any,
    user: any,
  ): void {
    const sheet = workbook.addWorksheet('Summary', {
      views: [{ state: 'frozen', xSplit: 0, ySplit: 3 }],
    });

    // Set column widths
    sheet.columns = [
      { width: 30 },
      { width: 20 },
      { width: 15 },
    ];

    // Title
    sheet.mergeCells('A1:C1');
    const titleCell = sheet.getCell('A1');
    titleCell.value = `${this.getReportTitle(reportType)}`;
    titleCell.font = { size: 16, bold: true, color: { argb: this.colors.primary } };
    titleCell.alignment = { horizontal: 'center', vertical: 'middle' };
    titleCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: this.colors.lightGray },
    };
    sheet.getRow(1).height = 30;

    // Metadata
    sheet.getCell('A2').value = 'Report Period:';
    sheet.getCell('B2').value = this.formatDateRange(startDate, endDate);
    sheet.getCell('A3').value = 'Generated By:';
    sheet.getCell('B3').value = user?.name || 'System';
    sheet.getCell('A4').value = 'Generated Date:';
    sheet.getCell('B4').value = new Date();
    sheet.getCell('B4').numFmt = 'mm/dd/yyyy hh:mm AM/PM';

    // Style metadata
    ['A2', 'A3', 'A4'].forEach((cell) => {
      sheet.getCell(cell).font = { bold: true };
    });

    // Key Metrics Header
    sheet.getRow(6).height = 25;
    sheet.mergeCells('A6:C6');
    const metricsHeader = sheet.getCell('A6');
    metricsHeader.value = 'KEY METRICS';
    metricsHeader.font = { size: 14, bold: true, color: { argb: this.colors.white } };
    metricsHeader.alignment = { horizontal: 'center', vertical: 'middle' };
    metricsHeader.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: this.colors.primary },
    };

    // Key Metrics Table
    const summary = reportData.summary;
    const metrics = [
      ['Metric', 'Value', 'Unit'],
      ['Total Energy Generated', summary.totalEnergyKWh.toFixed(2), 'kWh'],
      ['Average Power', summary.avgPowerW.toFixed(2), 'W'],
      ['Peak Power', summary.peakPowerW.toFixed(2), 'W'],
      ['CO₂ Avoided', summary.co2AvoidedKg.toFixed(2), 'kg'],
      ['Cost Savings', `$${summary.costSavingsUSD.toFixed(2)}`, 'USD'],
      ['Total Readings', summary.readingCount.toLocaleString(), 'readings'],
    ];

    let row = 7;
    for (const metric of metrics) {
      sheet.getCell(`A${row}`).value = metric[0];
      sheet.getCell(`B${row}`).value = metric[1];
      sheet.getCell(`C${row}`).value = metric[2];

      // Header row styling
      if (row === 7) {
        ['A', 'B', 'C'].forEach((col) => {
          const cell = sheet.getCell(`${col}${row}`);
          cell.font = { bold: true };
          cell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: this.colors.lightGray },
          };
        });
      }

      // Add borders
      ['A', 'B', 'C'].forEach((col) => {
        sheet.getCell(`${col}${row}`).border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' },
        };
      });

      row++;
    }
  }

  /**
   * Add Energy Performance Sheet
   * 
   * Detailed energy statistics.
   */
  private addEnergyPerformanceSheet(workbook: ExcelJS.Workbook, reportData: any): void {
    const sheet = workbook.addWorksheet('Energy Performance');

    // Set column widths
    sheet.columns = [
      { width: 30 },
      { width: 20 },
      { width: 15 },
    ];

    // Title
    sheet.mergeCells('A1:C1');
    this.setHeaderCell(sheet.getCell('A1'), 'Energy Performance');

    // Data
    const energy = reportData.energySummary;
    const data = [
      ['Metric', 'Value', 'Unit'],
      ['Total Energy Generated', energy.totalEnergyKWh.toFixed(3), 'kWh'],
      ['Average Power', energy.avgPowerW.toFixed(2), 'W'],
      ['Peak Power', energy.peakPowerW.toFixed(2), 'W'],
      ['Minimum Power', energy.minPowerW.toFixed(2), 'W'],
      ['Total Power Sum', energy.totalPowerW.toFixed(2), 'W'],
      ['Total Readings', energy.readingCount.toLocaleString(), 'readings'],
    ];

    this.addDataTable(sheet, data, 3);
  }

  /**
   * Add Environmental Impact Sheet
   * 
   * Green metrics and environmental benefits.
   */
  private addEnvironmentalImpactSheet(workbook: ExcelJS.Workbook, reportData: any): void {
    const sheet = workbook.addWorksheet('Environmental Impact');

    // Set column widths
    sheet.columns = [
      { width: 35 },
      { width: 20 },
      { width: 15 },
    ];

    // Title
    sheet.mergeCells('A1:C1');
    this.setHeaderCell(sheet.getCell('A1'), 'Environmental Impact');

    // Data
    const impact = reportData.environmentalImpact;
    const data = [
      ['Metric', 'Value', 'Unit'],
      ['Energy Generated', impact.energyGeneratedKWh.toFixed(3), 'kWh'],
      ['CO₂ Emissions Avoided', impact.co2AvoidedKg.toFixed(2), 'kg'],
      ['Trees Equivalent (1 year)', impact.treesEquivalent.toFixed(1), 'trees'],
      ['Coal Not Burned', impact.coalNotBurnedKg.toFixed(2), 'kg'],
      ['Homes Powered', impact.homesPoweredDays.toFixed(1), 'home-days'],
      ['Phone Charges Equivalent', impact.phoneChargesEquivalent.toLocaleString(), 'charges'],
    ];

    this.addDataTable(sheet, data, 3);

    // Add note
    sheet.getCell('A10').value = 'Note:';
    sheet.getCell('A10').font = { bold: true };
    sheet.mergeCells('B10:C10');
    sheet.getCell('B10').value = impact.calculationNotes;
    sheet.getCell('B10').alignment = { wrapText: true };
    sheet.getRow(10).height = 40;
  }

  /**
   * Add Cost Savings Sheet
   * 
   * Financial analysis and projections.
   */
  private addCostSavingsSheet(workbook: ExcelJS.Workbook, reportData: any): void {
    const sheet = workbook.addWorksheet('Cost Savings');

    // Set column widths
    sheet.columns = [
      { width: 30 },
      { width: 20 },
      { width: 15 },
    ];

    // Title
    sheet.mergeCells('A1:C1');
    this.setHeaderCell(sheet.getCell('A1'), 'Cost Savings Analysis');

    // Data
    const cost = reportData.costSavings;
    const data = [
      ['Period', 'Savings', 'Energy'],
      ['Electricity Rate', `$${cost.electricityRatePerKWh.toFixed(2)}/kWh`, '-'],
      ['Report Period', `$${cost.totalSavings.toFixed(2)}`, `${cost.energyGeneratedKWh.toFixed(2)} kWh`],
      ['Daily Average', `$${cost.dailyAverageSavings.toFixed(2)}`, `${(cost.energyGeneratedKWh / cost.periodDays).toFixed(2)} kWh`],
      ['Monthly Projected', `$${cost.monthlyProjectedSavings.toFixed(2)}`, `${(cost.monthlyProjectedSavings / cost.electricityRatePerKWh).toFixed(2)} kWh`],
      ['Yearly Projected', `$${cost.yearlyProjectedSavings.toFixed(2)}`, `${(cost.yearlyProjectedSavings / cost.electricityRatePerKWh).toFixed(2)} kWh`],
    ];

    this.addDataTable(sheet, data, 3);

    // Highlight electricity rate
    sheet.getCell('A4').font = { bold: true, color: { argb: this.colors.warning } };
  }

  /**
   * Add Peak Generation Sheet
   * 
   * Highest power generation details.
   */
  private addPeakGenerationSheet(workbook: ExcelJS.Workbook, reportData: any): void {
    const sheet = workbook.addWorksheet('Peak Generation');

    // Set column widths
    sheet.columns = [
      { width: 30 },
      { width: 30 },
    ];

    // Title
    sheet.mergeCells('A1:B1');
    this.setHeaderCell(sheet.getCell('A1'), 'Peak Generation');

    // Data
    const peak = reportData.peakGeneration;
    const data = [
      ['Attribute', 'Value'],
      ['Peak Power', `${peak.peakPowerW.toFixed(2)} W`],
      ['Date', peak.date],
      ['Time', peak.time],
      ['Sensor Name', peak.sensorName],
      ['Sensor Location', peak.sensorLocation],
      ['Sensor ID', peak.sensorId],
    ];

    this.addDataTable(sheet, data, 3);
  }

  /**
   * Helper: Set Header Cell
   */
  private setHeaderCell(cell: ExcelJS.Cell, text: string): void {
    cell.value = text;
    cell.font = { size: 14, bold: true, color: { argb: this.colors.white } };
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: this.colors.primary },
    };
    cell.border = {
      top: { style: 'thin' },
      left: { style: 'thin' },
      bottom: { style: 'thin' },
      right: { style: 'thin' },
    };
  }

  /**
   * Helper: Add Data Table
   */
  private addDataTable(sheet: ExcelJS.Worksheet, data: any[][], startRow: number): void {
    let row = startRow;

    for (let i = 0; i < data.length; i++) {
      const rowData = data[i];

      for (let col = 0; col < rowData.length; col++) {
        const colLetter = String.fromCharCode(65 + col); // A, B, C...
        const cell = sheet.getCell(`${colLetter}${row}`);
        cell.value = rowData[col];

        // Header row styling
        if (i === 0) {
          cell.font = { bold: true };
          cell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: this.colors.lightGray },
          };
        }

        // Add borders
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' },
        };

        // Alternate row colors (except header)
        if (i > 0 && i % 2 === 0) {
          cell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'FFF9FAFB' }, // Very light gray
          };
        }
      }

      row++;
    }
  }

  /**
   * Helper: Get Report Title
   */
  private getReportTitle(reportType: ReportType): string {
    const titles = {
      daily: 'Daily Energy Report',
      weekly: 'Weekly Energy Report',
      monthly: 'Monthly Energy Report',
      custom: 'Custom Energy Report',
    };
    return titles[reportType] || 'Energy Report';
  }

  /**
   * Helper: Format Date Range
   */
  private formatDateRange(startDate: string, endDate: string): string {
    if (startDate === endDate) {
      return this.formatDate(new Date(startDate));
    }
    return `${this.formatDate(new Date(startDate))} - ${this.formatDate(new Date(endDate))}`;
  }

  /**
   * Helper: Format Date
   */
  private formatDate(date: Date): string {
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  }
}
