import { Injectable, Logger } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import * as fs from 'fs';
import { ReportType } from '../schemas/report.schema';

/**
 * PDF Generator Service
 *
 * Generates professional PDF reports using PDFKit.
 *
 * Features:
 * - Clean, professional design
 * - Header with logo and title
 * - Sections for all metrics
 * - Environmental impact visualization
 * - Cost savings breakdown
 * - Footer with metadata
 *
 * Template Sections:
 * 1. Header (Title, Date Range, Generated By)
 * 2. Executive Summary (Key Metrics)
 * 3. Energy Performance (Detailed Stats)
 * 4. Environmental Impact (CO2, Trees, etc.)
 * 5. Cost Savings (Total, Projections)
 * 6. Peak Generation (If available)
 * 7. Footer (Generated Date, Page Number)
 */
@Injectable()
export class PdfGeneratorService {
  private readonly logger = new Logger(PdfGeneratorService.name);

  // Colors (professional palette)
  private readonly colors = {
    primary: '#2563EB', // Blue
    success: '#10B981', // Green
    warning: '#F59E0B', // Orange
    danger: '#EF4444', // Red
    gray: '#6B7280',
    lightGray: '#F3F4F6',
    darkGray: '#374151',
    white: '#FFFFFF',
  };

  /**
   * Generate PDF Report
   *
   * Creates a PDF report file with all sections.
   *
   * @param filePath - Path where PDF will be saved
   * @param reportType - Type of report
   * @param startDate - Report start date
   * @param endDate - Report end date
   * @param reportData - Report data from AnalyticsService
   * @param user - User who generated the report
   * @returns Promise<void>
   */
  async generate(
    filePath: string,
    reportType: ReportType,
    startDate: string,
    endDate: string,
    reportData: any,
    user: any,
  ): Promise<void> {
    this.logger.log(`Generating PDF report: ${filePath}`);

    return new Promise((resolve, reject) => {
      try {
        // Create PDF document
        const doc = new PDFDocument({
          size: 'A4',
          margins: {
            top: 50,
            bottom: 50,
            left: 50,
            right: 50,
          },
          info: {
            Title: `${this.getReportTitle(reportType)} - Energy Report`,
            Author: user?.name || 'Energy Monitoring System',
            Subject: 'Solar Energy Report',
            Keywords: 'energy, solar, report, analytics',
          },
        });

        // Pipe to file
        const stream = fs.createWriteStream(filePath);
        doc.pipe(stream);

        // Generate report sections
        this.addHeader(doc, reportType, startDate, endDate, user);
        this.addExecutiveSummary(doc, reportData);
        this.addEnergyPerformance(doc, reportData);
        this.addEnvironmentalImpact(doc, reportData);
        this.addCostSavings(doc, reportData);

        if (reportData.peakGeneration) {
          this.addPeakGeneration(doc, reportData);
        }

        this.addFooter(doc);

        // Finalize PDF
        doc.end();

        // Wait for stream to finish
        stream.on('finish', () => {
          this.logger.log(`PDF report generated successfully: ${filePath}`);
          resolve();
        });

        stream.on('error', (error) => {
          this.logger.error(`Error writing PDF: ${error.message}`);
          reject(error);
        });
      } catch (error) {
        this.logger.error(`Error generating PDF: ${error.message}`);
        reject(error);
      }
    });
  }

  /**
   * Add Header Section
   *
   * Adds report title, date range, and generated by information.
   */
  private addHeader(
    doc: typeof PDFDocument,
    reportType: ReportType,
    startDate: string,
    endDate: string,
    user: any,
  ): void {
    // Title
    doc
      .fontSize(24)
      .fillColor(this.colors.primary)
      .font('Helvetica-Bold')
      .text(this.getReportTitle(reportType), { align: 'center' });

    doc.moveDown(0.5);

    // Report subtitle
    doc
      .fontSize(12)
      .fillColor(this.colors.gray)
      .font('Helvetica')
      .text('Solar Energy Monitoring Report', { align: 'center' });

    doc.moveDown(1);

    // Date range box
    const boxY = doc.y;
    doc
      .roundedRect(50, boxY, 495, 60, 5)
      .fillAndStroke(this.colors.lightGray, this.colors.gray);

    doc.fillColor(this.colors.darkGray).fontSize(10).font('Helvetica-Bold');

    // Report Period
    doc.text('Report Period:', 70, boxY + 15, { continued: false });
    doc
      .font('Helvetica')
      .text(this.formatDateRange(startDate, endDate), 70, boxY + 30);

    // Generated By
    doc.font('Helvetica-Bold').text('Generated By:', 300, boxY + 15);
    doc.font('Helvetica').text(user?.name || 'System', 300, boxY + 30);

    // Generated Date
    doc.font('Helvetica-Bold').text('Generated Date:', 430, boxY + 15);
    doc.font('Helvetica').text(this.formatDate(new Date()), 430, boxY + 30);

    doc.moveDown(3);
  }

  /**
   * Add Executive Summary Section
   *
   * Displays key metrics in a grid layout.
   */
  private addExecutiveSummary(doc: typeof PDFDocument, reportData: any): void {
    this.addSectionTitle(doc, 'Executive Summary');

    const summary = reportData.summary;
    const y = doc.y;

    // Metric cards in 2x3 grid
    const metrics = [
      {
        label: 'Total Energy Generated',
        value: `${summary.totalEnergyKWh.toFixed(2)} kWh`,
        color: this.colors.primary,
      },
      {
        label: 'Average Power',
        value: `${summary.avgPowerW.toFixed(0)} W`,
        color: this.colors.success,
      },
      {
        label: 'Peak Power',
        value: `${summary.peakPowerW.toFixed(0)} W`,
        color: this.colors.warning,
      },
      {
        label: 'CO₂ Avoided',
        value: `${summary.co2AvoidedKg.toFixed(2)} kg`,
        color: this.colors.success,
      },
      {
        label: 'Cost Savings',
        value: `$${summary.costSavingsUSD.toFixed(2)}`,
        color: this.colors.primary,
      },
      {
        label: 'Total Readings',
        value: summary.readingCount.toLocaleString(),
        color: this.colors.gray,
      },
    ];

    // Draw 2x3 grid
    for (let i = 0; i < metrics.length; i++) {
      const row = Math.floor(i / 2);
      const col = i % 2;
      const x = 50 + col * 255;
      const cardY = y + row * 70;

      this.addMetricCard(doc, x, cardY, 240, metrics[i]);
    }

    doc.y = y + 220; // Move past the grid
    doc.moveDown(1);
  }

  /**
   * Add Energy Performance Section
   *
   * Detailed energy statistics.
   */
  private addEnergyPerformance(doc: typeof PDFDocument, reportData: any): void {
    this.addSectionTitle(doc, 'Energy Performance');

    const energy = reportData.energySummary;

    const data = [
      ['Metric', 'Value', 'Unit'],
      ['Total Energy Generated', energy.totalEnergyKWh.toFixed(3), 'kWh'],
      ['Average Power', energy.avgPowerW.toFixed(2), 'W'],
      ['Peak Power', energy.peakPowerW.toFixed(2), 'W'],
      ['Minimum Power', energy.minPowerW.toFixed(2), 'W'],
      ['Total Readings', energy.readingCount.toLocaleString(), 'readings'],
    ];

    this.addTable(doc, data);
    doc.moveDown(1);
  }

  /**
   * Add Environmental Impact Section
   *
   * CO2, trees, coal, homes powered, etc.
   */
  private addEnvironmentalImpact(
    doc: typeof PDFDocument,
    reportData: any,
  ): void {
    this.addSectionTitle(doc, 'Environmental Impact');

    const impact = reportData.environmentalImpact;

    doc
      .fontSize(10)
      .fillColor(this.colors.gray)
      .font('Helvetica')
      .text(
        'Your solar energy generation has made a positive environmental impact:',
        { align: 'left' },
      );

    doc.moveDown(0.5);

    // Impact items
    const impacts = [
      {
        icon: '🌍',
        label: 'CO₂ Emissions Avoided',
        value: `${impact.co2AvoidedKg.toFixed(2)} kg`,
      },
      {
        icon: '🌳',
        label: 'Equivalent to Trees Planted',
        value: `${impact.treesEquivalent.toFixed(1)} trees (for 1 year)`,
      },
      {
        icon: '⚫',
        label: 'Coal Not Burned',
        value: `${impact.coalNotBurnedKg.toFixed(2)} kg`,
      },
      {
        icon: '🏠',
        label: 'Homes Powered',
        value: `${impact.homesPoweredDays.toFixed(1)} home-days`,
      },
      {
        icon: '📱',
        label: 'Phone Charges',
        value: `${impact.phoneChargesEquivalent.toLocaleString()} charges`,
      },
    ];

    for (const item of impacts) {
      doc
        .fontSize(20)
        .text(item.icon, 70, doc.y, { continued: true, width: 30 });

      doc
        .fontSize(10)
        .fillColor(this.colors.darkGray)
        .font('Helvetica-Bold')
        .text(item.label, 110, doc.y - 5, { continued: false });

      doc
        .fontSize(12)
        .fillColor(this.colors.success)
        .font('Helvetica-Bold')
        .text(item.value, 110, doc.y + 2);

      doc.moveDown(1);
    }

    doc.moveDown(0.5);
  }

  /**
   * Add Cost Savings Section
   *
   * Financial impact and projections.
   */
  private addCostSavings(doc: typeof PDFDocument, reportData: any): void {
    this.addSectionTitle(doc, 'Cost Savings');

    const cost = reportData.costSavings;

    doc
      .fontSize(10)
      .fillColor(this.colors.gray)
      .font('Helvetica')
      .text(
        `Based on electricity rate of $${cost.electricityRatePerKWh.toFixed(2)}/kWh:`,
        { align: 'left' },
      );

    doc.moveDown(0.5);

    const data = [
      ['Period', 'Savings', 'Energy'],
      [
        'Total Period',
        `$${cost.totalSavings.toFixed(2)}`,
        `${cost.energyGeneratedKWh.toFixed(2)} kWh`,
      ],
      [
        'Daily Average',
        `$${cost.dailyAverageSavings.toFixed(2)}`,
        `${(cost.energyGeneratedKWh / cost.periodDays).toFixed(2)} kWh`,
      ],
      [
        'Monthly Projected',
        `$${cost.monthlyProjectedSavings.toFixed(2)}`,
        `${(cost.monthlyProjectedSavings / cost.electricityRatePerKWh).toFixed(2)} kWh`,
      ],
      [
        'Yearly Projected',
        `$${cost.yearlyProjectedSavings.toFixed(2)}`,
        `${(cost.yearlyProjectedSavings / cost.electricityRatePerKWh).toFixed(2)} kWh`,
      ],
    ];

    this.addTable(doc, data);
    doc.moveDown(1);
  }

  /**
   * Add Peak Generation Section
   *
   * Highest power generation moment.
   */
  private addPeakGeneration(doc: typeof PDFDocument, reportData: any): void {
    this.addSectionTitle(doc, 'Peak Generation');

    const peak = reportData.peakGeneration;

    doc
      .fontSize(10)
      .fillColor(this.colors.gray)
      .font('Helvetica')
      .text('Highest power generation recorded during this period:', {
        align: 'left',
      });

    doc.moveDown(0.5);

    const data = [
      ['Attribute', 'Value'],
      ['Peak Power', `${peak.peakPowerW.toFixed(2)} W`],
      ['Date', peak.date],
      ['Time', peak.time],
      ['Sensor', peak.sensorName],
      ['Location', peak.sensorLocation],
    ];

    this.addTable(doc, data);
    doc.moveDown(1);
  }

  /**
   * Add Footer
   *
   * Report metadata and disclaimer.
   */
  private addFooter(doc: typeof PDFDocument): void {
    const pageCount = doc.bufferedPageRange().count;

    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);

      // Footer line
      doc.moveTo(50, 770).lineTo(545, 770).stroke(this.colors.lightGray);

      // Footer text
      doc
        .fontSize(8)
        .fillColor(this.colors.gray)
        .font('Helvetica')
        .text('Generated by Energy Monitoring System', 50, 775, {
          align: 'left',
          width: 250,
        });

      doc.text(`Page ${i + 1} of ${pageCount}`, 300, 775, {
        align: 'right',
        width: 245,
      });
    }
  }

  /**
   * Helper: Add Section Title
   */
  private addSectionTitle(doc: typeof PDFDocument, title: string): void {
    doc
      .fontSize(14)
      .fillColor(this.colors.primary)
      .font('Helvetica-Bold')
      .text(title, { align: 'left' });

    doc.moveDown(0.5);
  }

  /**
   * Helper: Add Metric Card
   */
  private addMetricCard(
    doc: typeof PDFDocument,
    x: number,
    y: number,
    width: number,
    metric: any,
  ): void {
    // Card background
    doc
      .roundedRect(x, y, width, 60, 3)
      .fillAndStroke(this.colors.white, metric.color);

    // Label
    doc
      .fontSize(9)
      .fillColor(this.colors.gray)
      .font('Helvetica')
      .text(metric.label, x + 10, y + 10, { width: width - 20 });

    // Value
    doc
      .fontSize(16)
      .fillColor(metric.color)
      .font('Helvetica-Bold')
      .text(metric.value, x + 10, y + 30, { width: width - 20 });
  }

  /**
   * Helper: Add Table
   */
  private addTable(doc: typeof PDFDocument, data: string[][]): void {
    const startY = doc.y;
    const cellPadding = 8;
    const rowHeight = 25;
    const colWidths = [200, 150, 145]; // Adjust based on columns

    // Header row
    const header = data[0];
    let currentX = 50;

    for (let col = 0; col < header.length; col++) {
      doc
        .rect(currentX, startY, colWidths[col], rowHeight)
        .fillAndStroke(this.colors.primary, this.colors.primary);

      doc
        .fontSize(10)
        .fillColor(this.colors.white)
        .font('Helvetica-Bold')
        .text(header[col], currentX + cellPadding, startY + cellPadding, {
          width: colWidths[col] - cellPadding * 2,
        });

      currentX += colWidths[col];
    }

    // Data rows
    for (let row = 1; row < data.length; row++) {
      const rowData = data[row];
      const currentY = startY + row * rowHeight;
      currentX = 50;

      // Alternate row colors
      const bgColor = row % 2 === 0 ? this.colors.white : this.colors.lightGray;

      for (let col = 0; col < rowData.length; col++) {
        doc
          .rect(currentX, currentY, colWidths[col], rowHeight)
          .fillAndStroke(bgColor, this.colors.lightGray);

        doc
          .fontSize(9)
          .fillColor(this.colors.darkGray)
          .font('Helvetica')
          .text(rowData[col], currentX + cellPadding, currentY + cellPadding, {
            width: colWidths[col] - cellPadding * 2,
          });

        currentX += colWidths[col];
      }
    }

    doc.y = startY + data.length * rowHeight + 10;
  }

  /**
   * Helper: Get Report Title
   */
  private getReportTitle(reportType: ReportType): string {
    const titles = {
      daily: 'Daily Energy Report',
      weekly: 'Weekly Energy Report',
      monthly: 'Monthly Energy Report',
      custom: 'Custom Energy Report',
    };
    return titles[reportType] || 'Energy Report';
  }

  /**
   * Helper: Format Date Range
   */
  private formatDateRange(startDate: string, endDate: string): string {
    if (startDate === endDate) {
      return this.formatDate(new Date(startDate));
    }
    return `${this.formatDate(new Date(startDate))} - ${this.formatDate(new Date(endDate))}`;
  }

  /**
   * Helper: Format Date
   */
  private formatDate(date: Date): string {
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  }
}
