import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

/**
 * Report Type Enum
 * 
 * Defines the types of reports that can be generated.
 */
export enum ReportType {
  DAILY = 'daily',
  WEEKLY = 'weekly',
  MONTHLY = 'monthly',
  CUSTOM = 'custom',
}

/**
 * Report Format Enum
 * 
 * Defines the file formats for generated reports.
 */
export enum ReportFormat {
  PDF = 'pdf',
  EXCEL = 'excel',
}

/**
 * Report Summary Interface
 * 
 * Stores key metrics from the report for quick access.
 */
export interface ReportSummary {
  totalEnergyKWh: number;
  avgPowerW: number;
  peakPowerW: number;
  co2AvoidedKg: number;
  costSavingsUSD: number;
  readingCount: number;
}

/**
 * Report Document Type
 * 
 * Represents a report document from MongoDB with Mongoose methods.
 */
export type ReportDocument = Report & Document;

/**
 * Report Schema
 * 
 * Stores metadata about generated reports.
 * Actual report files are stored in the file system.
 * 
 * Purpose:
 * - Track generated reports
 * - Enable report listing and management
 * - Store report metadata for quick access
 * - Implement auto-deletion (TTL)
 * 
 * Security:
 * - Reports are tied to the user who generated them
 * - Users can only access their own reports
 * - File paths are validated on access
 * 
 * Storage Strategy:
 * - Metadata: MongoDB (this collection)
 * - Files: File system (./uploads/reports/)
 * - Retention: 30 days (TTL index)
 */
@Schema({
  timestamps: true, // Automatically add createdAt and updatedAt
  collection: 'reports',
})
export class Report {
  /**
   * Report Type
   * 
   * The type of report generated.
   * 
   * Values:
   * - daily: Single day report
   * - weekly: Monday to Sunday report
   * - monthly: Full month report
   * - custom: User-specified date range
   */
  @Prop({
    required: true,
    enum: ReportType,
    index: true,
  })
  type: ReportType;

  /**
   * Report Format
   * 
   * The file format of the generated report.
   * 
   * Values:
   * - pdf: PDF document
   * - excel: Excel spreadsheet (.xlsx)
   */
  @Prop({
    required: true,
    enum: ReportFormat,
    index: true,
  })
  format: ReportFormat;

  /**
   * File Name
   * 
   * The name of the generated file.
   * 
   * Format: {type}-report-{period}-{timestamp}.{ext}
   * Example: monthly-report-2026-07-1721300400000.pdf
   * 
   * Unique: Yes (timestamp ensures uniqueness)
   */
  @Prop({
    required: true,
    unique: true,
  })
  fileName: string;

  /**
   * File Path
   * 
   * Relative path to the report file.
   * 
   * Format: uploads/reports/{fileName}
   * Example: uploads/reports/monthly-report-2026-07-1721300400000.pdf
   * 
   * Security:
   * - Always validated before access
   * - Must be within uploads/reports/ directory
   * - No directory traversal allowed
   */
  @Prop({
    required: true,
  })
  filePath: string;

  /**
   * File Size
   * 
   * Size of the generated file in bytes.
   * 
   * Used for:
   * - Display to user
   * - Storage monitoring
   * - Cleanup decisions
   */
  @Prop({
    required: true,
  })
  fileSize: number;

  /**
   * Generated By
   * 
   * Reference to the user who generated this report.
   * 
   * Purpose:
   * - Ownership tracking
   * - Access control (users can only see their reports)
   * - "Generated By" field in report header
   * 
   * Type: MongoDB ObjectId reference to User collection
   */
  @Prop({
    required: true,
    type: Types.ObjectId,
    ref: 'User',
    index: true, // Index for fast user queries
  })
  generatedBy: Types.ObjectId;

  /**
   * Start Date
   * 
   * The start date of the report period.
   * 
   * Format: YYYY-MM-DD
   * Example: 2026-07-01
   * 
   * Used for:
   * - Display in report
   * - Filtering reports
   * - Validation
   */
  @Prop({
    required: true,
    index: true,
  })
  startDate: string;

  /**
   * End Date
   * 
   * The end date of the report period.
   * 
   * Format: YYYY-MM-DD
   * Example: 2026-07-31
   * 
   * Used for:
   * - Display in report
   * - Filtering reports
   * - Validation
   */
  @Prop({
    required: true,
    index: true,
  })
  endDate: string;

  /**
   * Parameters
   * 
   * Additional parameters used when generating the report.
   * 
   * Stored as flexible JSON object.
   * 
   * Example:
   * {
   *   sensorId: "64f9a1b2...",
   *   includeCharts: true,
   *   electricityRate: 0.12
   * }
   * 
   * Future use:
   * - Sensor filtering
   * - Custom calculations
   * - Report options
   */
  @Prop({
    type: Object,
    default: {},
  })
  parameters: Record<string, any>;

  /**
   * Summary
   * 
   * Key metrics from the report for quick access.
   * 
   * Stored for:
   * - Quick display without opening file
   * - Report listing
   * - Search and filtering
   * 
   * Contains:
   * - totalEnergyKWh: Total energy generated
   * - avgPowerW: Average power
   * - peakPowerW: Peak power
   * - co2AvoidedKg: CO2 emissions avoided
   * - costSavingsUSD: Cost savings
   * - readingCount: Number of sensor readings
   */
  @Prop({
    type: Object,
    required: true,
  })
  summary: ReportSummary;

  /**
   * Download Count
   * 
   * Number of times this report has been downloaded.
   * 
   * Incremented on each download.
   * 
   * Used for:
   * - Analytics (which reports are popular)
   * - Cleanup decisions (don't delete frequently accessed)
   */
  @Prop({
    default: 0,
  })
  downloadCount: number;

  /**
   * Expires At
   * 
   * When this report should be automatically deleted.
   * 
   * Default: 30 days from creation
   * 
   * TTL Index:
   * - MongoDB automatically deletes documents when expiresAt is reached
   * - TTL index declared at schema level (see ReportSchema.index below)
   * - File cleanup job should also delete the physical file
   * 
   * Purpose:
   * - Automatic cleanup
   * - Storage management
   * - Compliance (data retention policies)
   * 
   * Note: index: true removed to avoid duplicate with TTL index
   */
  @Prop({
    required: true,
  })
  expiresAt: Date;

  /**
   * Timestamps
   * 
   * Automatically managed by Mongoose timestamps option:
   * - createdAt: When report was generated
   * - updatedAt: When report metadata was last modified
   */
}

/**
 * Report Schema Factory
 * 
 * Creates the Mongoose schema from the class definition.
 */
export const ReportSchema = SchemaFactory.createForClass(Report);

/**
 * Schema Indexes
 * 
 * Additional compound indexes for optimized queries.
 * 
 * 1. User's reports sorted by creation date
 *    - Most common query: Get user's reports, newest first
 *    - Used in report listing endpoint
 * 
 * 2. Type and format filtering
 *    - Common query: Get all PDF monthly reports
 *    - Used in filtered listing
 * 
 * 3. Date range queries
 *    - Query: Get reports for specific time period
 *    - Used in report search
 */
ReportSchema.index({ generatedBy: 1, createdAt: -1 });
ReportSchema.index({ type: 1, format: 1, createdAt: -1 });
ReportSchema.index({ startDate: 1, endDate: 1 });

/**
 * TTL Index for Auto-Deletion
 * 
 * MongoDB will automatically delete documents when expiresAt is reached.
 * 
 * expireAfterSeconds: 0 means delete immediately when time is reached.
 * 
 * Note: Background task runs every 60 seconds, so deletion may not be instant.
 */
ReportSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

/**
 * Schema Transformation
 * 
 * Transform the document when converting to JSON (for API responses).
 * 
 * Changes:
 * - Rename _id to id
 * - Remove __v (version key)
 * - Keep all other fields
 */
ReportSchema.set('toJSON', {
  transform: (doc, ret: any) => {
    ret.id = ret._id.toString();
    delete ret._id;
    delete ret.__v;
    return ret;
  },
});
