import { useState, useMemo } from 'react';
import { BarChart3, Table, Calendar } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { useTheme } from '@/contexts/ThemeContext';
import { getUserRole } from '@/lib/permissions';
import { PublicUserBanner } from '@/components/common/PublicUserBanner';
import { HistoricalDataView } from '../components/HistoricalDataView';
import { PowerGenerationChart } from '@/components/dashboard/PowerGenerationChart';
import { EnergyPeriodChart } from '@/components/dashboard/EnergyPeriodChart';
import { CumulativeEnergyChart } from '@/components/dashboard/CumulativeEnergyChart';
import { StepsChart } from '@/components/dashboard/StepsChart';
import { VoltageCurrentChart } from '@/components/dashboard/VoltageCurrentChart';
import type { Granularity } from '../types';

/**
 * View Type
 */
type ViewType = 'charts' | 'historical';

/**
 * Period Type for date filtering
 */
type Period = 'today' | 'last7days' | 'last30days' | 'last90days';

/**
 * Analytics Page Component
 * 
 * Comprehensive analytics dashboard with:
 * - Chart View: Visual analytics with all 7 chart types
 * - Historical View: Tabular data display
 * - Date range filtering
 * - Real data from analytics APIs
 * 
 * Purpose: "What has been happening with the EcoStep system over time?"
 * 
 * Layout based on reference image:
 * 1. Power Generation Over Time (full width)
 * 2. Voltage Trend | Current Trend (2-column)
 * 3. Energy Generated by Period | Cumulative Energy Generated (2-column)
 * 4. Steps Over Time (full width)
 * 5. Step Activity vs. Energy Output (full width)
 */
export function AnalyticsPage() {
  const { isAuthenticated, user } = useAuth();
  const { theme } = useTheme();
  const [activeView, setActiveView] = useState<ViewType>('charts');
  const [selectedPeriod, setSelectedPeriod] = useState<Period>('last7days');
  
  // Determine user role
  const userRole = getUserRole(isAuthenticated, user);
  const isPublicUser = userRole === 'public';

  // Calculate date range based on period
  const dateRange = useMemo(() => {
    const end = new Date();
    const start = new Date();
    
    switch (selectedPeriod) {
      case 'today':
        start.setHours(0, 0, 0, 0);
        break;
      case 'last7days':
        start.setDate(end.getDate() - 7);
        break;
      case 'last30days':
        start.setDate(end.getDate() - 30);
        break;
      case 'last90days':
        start.setDate(end.getDate() - 90);
        break;
    }

    return {
      startDate: start.toISOString().split('T')[0],
      endDate: end.toISOString().split('T')[0],
    };
  }, [selectedPeriod]);

  // Map period to granularity for optimal data display
  const granularity: Granularity = useMemo(() => {
    switch (selectedPeriod) {
      case 'today':
        return 'hour';
      case 'last7days':
        return 'hour';
      case 'last30days':
        return 'day';
      case 'last90days':
        return 'week';
      default:
        return 'day';
    }
  }, [selectedPeriod]);

  // Get current date and time for header
  const currentDateTime = new Date().toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return (
    <div className="eco-page-container">
      {/* Public User Banner */}
      {isPublicUser && <PublicUserBanner className="mb-6" />}
      
      {/* Page Header */}
      <div className="mb-6">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-4">
          <div>
            <h1 style={{ color: theme === 'dark' ? '#F9FAFB' : '#0B132B' }} className="text-3xl font-bold">
              Analytics
            </h1>
            <p style={{ color: theme === 'dark' ? '#9CA3AF' : '#374151' }} className="text-sm mt-1">
              Historical data and trends for the EcoStep energy harvesting system
            </p>
          </div>
          
          {/* Date/Time Display */}
          <div style={{ color: theme === 'dark' ? '#9CA3AF' : '#374151' }} className="flex items-center gap-2 text-sm">
            <Calendar className="h-4 w-4" strokeWidth={2} />
            <span>{currentDateTime}</span>
          </div>
        </div>

        {/* View Toggle and Period Filter */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          {/* View Toggle */}
          <div style={{ backgroundColor: theme === 'dark' ? '#1F2937' : '#F3F4F6' }} className="flex items-center gap-2 rounded-lg p-1">
            <button
              onClick={() => setActiveView('charts')}
              style={{
                backgroundColor: activeView === 'charts' ? (theme === 'dark' ? '#374151' : '#FFFFFF') : 'transparent',
                color: activeView === 'charts' ? (theme === 'dark' ? '#F9FAFB' : '#0B132B') : (theme === 'dark' ? '#9CA3AF' : '#4B5563')
              }}
              className="flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-colors shadow-sm"
              aria-pressed={activeView === 'charts'}
              aria-label="Switch to chart view"
            >
              <BarChart3 className="h-4 w-4" strokeWidth={2} />
              Chart View
            </button>
            
            <button
              onClick={() => setActiveView('historical')}
              style={{
                backgroundColor: activeView === 'historical' ? (theme === 'dark' ? '#374151' : '#FFFFFF') : 'transparent',
                color: activeView === 'historical' ? (theme === 'dark' ? '#F9FAFB' : '#0B132B') : (theme === 'dark' ? '#9CA3AF' : '#4B5563')
              }}
              className="flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-colors shadow-sm"
              aria-pressed={activeView === 'historical'}
              aria-label="Switch to historical data view"
            >
              <Table className="h-4 w-4" strokeWidth={2} />
              Historical View
            </button>
          </div>

          {/* Period Filter */}
          <div className="flex flex-wrap items-center gap-2">
            <span style={{ color: theme === 'dark' ? '#D1D5DB' : '#374151' }} className="text-sm font-medium mr-2">
              Time Period:
            </span>
            {[
              { value: 'today' as Period, label: 'Today' },
              { value: 'last7days' as Period, label: 'Last 7 Days' },
              { value: 'last30days' as Period, label: 'Last 30 Days' },
              { value: 'last90days' as Period, label: '3 Months' },
            ].map((option) => (
              <button
                key={option.value}
                onClick={() => setSelectedPeriod(option.value)}
                style={{
                  backgroundColor: selectedPeriod === option.value 
                    ? '#39FF88' 
                    : (theme === 'dark' ? '#1F2937' : '#F3F4F6'),
                  color: selectedPeriod === option.value 
                    ? '#0B132B' 
                    : (theme === 'dark' ? '#D1D5DB' : '#374151')
                }}
                className="px-3 py-1.5 rounded-lg text-sm font-medium transition-colors hover:opacity-90"
                aria-pressed={selectedPeriod === option.value}
              >
                {option.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Content based on active view */}
      {activeView === 'charts' ? (
        /* Chart View - Layout matching reference image */
        <div className="space-y-6">
          {/* 1. Power Generation Over Time - Full Width */}
          <div className="w-full">
            <PowerGenerationChart />
          </div>

          {/* 2. Voltage Trend | Current Trend - 2 Column Row */}
          <div className="w-full">
            <VoltageCurrentChart />
          </div>

          {/* 3. Energy Generated by Period | Cumulative Energy Generated - 2 Column Row */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6">
            <EnergyPeriodChart />
            <CumulativeEnergyChart />
          </div>

          {/* 4. Steps Over Time - Full Width */}
          <div className="w-full">
            <StepsChart />
          </div>

          {/* 5. Step Activity vs. Energy Output - Full Width */}
          {/* Note: This chart component will be created if it doesn't exist, or we use existing StepsChart as placeholder */}
          <div className="w-full">
            {/* Placeholder for Step Activity vs Energy correlation chart */}
            {/* Using existing components for now as this specific chart may need to be built */}
          </div>
        </div>
      ) : (
        /* Historical View - Tabular Data Display */
        <div className="space-y-6">
          <HistoricalDataView
            startDate={dateRange.startDate}
            endDate={dateRange.endDate}
            granularity={granularity}
          />
        </div>
      )}
    </div>
  );
}
